const { jsPDF } = require("jspdf");

function createPremiumKundliPDF(data) {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.text("?? AstroPerfect Premium Kundli", 20, 20);

  doc.setFontSize(12);
  doc.text("Zodiac Details:", 20, 35);

  const zodiac = [
    ["Planet", "Sign", "House"],
    ["Sun", data.sun_sign, data.sun_house],
    ["Moon", data.moon_sign, data.moon_house],
    ["Mars", data.mars_sign, data.mars_house]
  ];

  let y = 45;
  zodiac.forEach((row) => {
    doc.text(row.join(" | "), 20, y);
    y += 10;
  });

  doc.setFontSize(10);
  doc.text("Generated by AstroPerfect", 20, y + 10);

  doc.save("Premium-Kundli.pdf");